name: Keep Render App Awake

on:
  schedule:
    - cron: "*/2 2-18 * * *"  # Every 2 minutes between 8 AM and 12 AM IST

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Render App
        run: |
          curl -s https://chatbot-final-hvuc.onrender.com/ping || echo "Ping failed"
