name: Keep Render App Awake

on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes (UTC)

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Render App
        run: |
          curl -s https://chatbot-final-hvuc.onrender.com/ping || echo "Ping failed"
